### ISSUE TITLE
Adaptive Solver too slow

### ISSUE THREAD

**Issue by Chris1221** [aaronshifman/modeling_final#3]
For some reason the reactive environment is **killing** the adaptive solver. Going to put it in a seperate branch for now, maybe pull it in eventually if I can figure out why its so slow. For now, going back to Eulers for speed.

**Comment by aaronshifman** [comment]
Hahahahahahahahahahaha - why we don't use R for diffy Qs

**Comment by Chris1221** [comment]
Lol :'( The reason I coulnd't figure out where I fucked up was because I didn't fuck up, my laptop was just too slow to load it. Loaded it on my mac mini, swore, walked away to get tea, and when I came back it had actually loaded. The world is a strange place :P Do you mind if we keep this model on the Euler?

**Comment by aaronshifman** [comment]
Lol, ya that's fine, it falls under the category of who cares :p

**Comment by Chris1221** [comment]
> "It's a feature, not a bug" 

That's our line on this one.
