### ISSUE TITLE
Frequency

### ISSUE THREAD

**Issue by aaronshifman** [aaronshifman/modeling_final#4]
Even restricted frequency measurements have weird values - want to look into it? Only spend a few minutes - if nothing jumps out dump it :p

**Comment by Chris1221** [comment]
Gotcha. At the pool, will take a look ASAP :)

**Comment by Chris1221** [comment]
Nice use of issues ;)

**Comment by Chris1221** [comment]
I changed your `peak_range` parameter from 0.95 to 0.75 (and a few others) and we lost that evening out after 20 that looked weird. I think that was just an artifact of how you were calculating the freq. What did you mean by restricted frequency? 

![freq](https://cloud.githubusercontent.com/assets/8516981/11824697/5440fd26-a349-11e5-8c41-3efd0d2a6d9c.png)

**Comment by aaronshifman** [comment]
The 0.95 was correct, it's a threshold on the frequency measurement. It ignores the oscillations from when it's not being stimulated. I bet if you you use the 0.75, and run it to say ~70 you'll get the same thing.

**Comment by Chris1221** [comment]
Kk, I'll change it back. :)
