### ISSUE TITLE
Partial derivative difference 

### ISSUE THREAD

**Issue by Chris1221** [aaronshifman/modeling_final#5]
I wish mathjax rendered here. I got a slightly different partial, see [here](http://www.wolframalpha.com/input/?i=derivative+of+V%28a%2BV%29%281%E2%88%92V%29%E2%88%92W%2Bz+wrt+V)

**Comment by Chris1221** [comment]
Wanna take a look when you have a second? I may have also made a mistake.

![image](https://cloud.githubusercontent.com/assets/8516981/11825734/cba4143e-a34e-11e5-9b2d-4fe8ff98bd5f.png)

**Comment by aaronshifman** [comment]
Third line to fourth line would be -2V(a+1) - so we both shit the bed, would you mind fixing that in the proposal?

**Comment by Chris1221** [comment]
Whoops yep you're right. I'll change it.

**Comment by aaronshifman** [comment]
Also can you change it in the script as well?

**Comment by Chris1221** [comment]
Eigenvalue plot is significantly different, maybe take a look?

**Comment by Chris1221** [comment]
You were right, they're equivalent and I'm stupid, but the eigenvalue plot DEFINITELY changed. Myabe there was a small mistake in the calculation of the eigenvalues before?
