### ISSUE TITLE
Sections remaining

### ISSUE THREAD

**Issue by Chris1221** [aaronshifman/modeling_final#6]
Stuff still have to add
- [x] Frequency for static
- [x] Images for 2 and n neurons for static
- [x] Model analysis for static + dynamic
- [x] Description of web app
- [x] Supplemental website (py viewer), but write an appendix to direct to this
- [x] Running header should change name by chapter?
  [proposal.pdf](https://github.com/aaronshifman/modeling_final/files/67900/proposal.pdf)
- [x] Conclusion

**Comment by aaronshifman** [comment]
I've chooched up the proposal with my annotations
